name: Build OS KianV RV32IMA ASIC Tinytaepout uLinux

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential device-tree-compiler cpio rsync file wget unzip bc

    - name: Build OS
      working-directory: asic/os/ulinux_asic_kianv_soc
      run: make all bootloader

    - name: Prepare artifact
      working-directory: asic/os/ulinux_asic_kianv_soc
      run: |
        mkdir -p artifact_files
        cp kianv.dtb bootloader/bootloader.bin buildroot/output/images/Image artifact_files

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ulinux_asic_kianv_soc_firmware
        path: asic/os/ulinux_asic_kianv_soc/artifact_files
